Repository SnobbyDragon/CSE3902_SP21, pull requests merged in 2021-03, with the labels that each got.

#202 Enemy specials
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Dodongo/Dodongo.cs
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Ganon/GanonFireball.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokNeck.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Bosses/Patra/PatraMinion.cs
  sprint0/sprint0/Collision/AllCollisionHandler.cs
  sprint0/sprint0/Collision/EnemyProjectileCollisionHandler.cs
  sprint0/sprint0/Collision/LinkProjectileCollisionHandler.cs
  sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs
  sprint0/sprint0/Enemies/Gel.cs
  sprint0/sprint0/Enemies/Goriya.cs
  sprint0/sprint0/Enemies/GoriyaBoomerang.cs
  sprint0/sprint0/Enemies/Keese.cs
  sprint0/sprint0/Enemies/Snake.cs
  sprint0/sprint0/Enemies/Stalfos.cs
  sprint0/sprint0/Enemies/Trap.cs
  sprint0/sprint0/Enemies/Wallmaster.cs
  sprint0/sprint0/Enemies/Zol.cs
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/IEnemy.cs
  sprint0/sprint0/IProjectile.cs
  sprint0/sprint0/Items/Arrow.cs
  sprint0/sprint0/Items/Bomb.cs
  sprint0/sprint0/Items/Boomerang.cs
  sprint0/sprint0/Items/Fairy.cs
  sprint0/sprint0/Weapons/Fireball.cs
  sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
  sprint0/sprint0/Weapons/SwordBeam.cs
Labels: new feature

#207 npcs are blocks
  sprint0/sprint0/Collision/AllCollisionHandler.cs
  sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs
  sprint0/sprint0/LoadLevel/LevelLoader.cs
  sprint0/sprint0/NPCs/Flame.cs
  sprint0/sprint0/NPCs/Merchant.cs
  sprint0/sprint0/NPCs/NpcsSpriteFactory.cs
  sprint0/sprint0/NPCs/OldPerson.cs
Labels: new feature

#231 gamepad controller
  sprint0/sprint0/Input/Controller/Gamepad.cs
Labels: new feature

#241 fireballs of statue and manhandla no longer follow link
  sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs
  sprint0/sprint0/Dungeon/Statue.cs
Labels: bug fix

#384 added sword classes
  sprint0/sprint0/Collision/LinkItemCollisionHandler.cs
  sprint0/sprint0/Content/LevelData/Room0.xml
  sprint0/sprint0/Content/LevelData/Room13.xml
  sprint0/sprint0/Content/LevelData/Room4.xml
  sprint0/sprint0/Content/LevelData/Room8.xml
  sprint0/sprint0/Content/LevelData/Room9.xml
  sprint0/sprint0/HUD/BombHUD.cs
  sprint0/sprint0/HUD/HUDManager.cs
  sprint0/sprint0/HUD/HeartHUD.cs
  sprint0/sprint0/HUD/KeyHUD.cs
  sprint0/sprint0/HUD/PopulateHUDInventory.cs
  sprint0/sprint0/HUD/RupeeHUD.cs
  sprint0/sprint0/Interfaces/IHUDInventory.cs
  sprint0/sprint0/Items/ItemsSpriteFactory.cs
  sprint0/sprint0/Items/MagicalKey.cs
  sprint0/sprint0/Items/MagicalRod.cs
  sprint0/sprint0/Items/MagicalSword.cs
  sprint0/sprint0/Items/WhiteSword.cs
  sprint0/sprint0/Items/WoodenSword.cs
  sprint0/sprint0/Link/Link.cs
Labels: new feature

#386 test mode
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Dodongo/Dodongo.cs
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Bosses/Patra/PatraMinion.cs
  sprint0/sprint0/Collision/LinkItemCollisionHandler.cs
  sprint0/sprint0/Content/LevelData/Room9.xml
  sprint0/sprint0/Dungeon/Statue.cs
  sprint0/sprint0/Enemies/Enemy.cs
  sprint0/sprint0/Enemies/Trapparatus.cs
  sprint0/sprint0/Enemies/Zol.cs
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDItemMapping.cs
  sprint0/sprint0/Input/Command/NextRoomCommand.cs
  sprint0/sprint0/Input/Command/PreviousRoomCommand.cs
  sprint0/sprint0/Input/Command/ToggleTestModeCommand.cs
  sprint0/sprint0/Input/Controller/KeyboardController.cs
  sprint0/sprint0/Link/Link.cs
  sprint0/sprint0/Link/LinkUseItemHelper.cs
  sprint0/sprint0/LoadLevel/LoadLevel.cs
  sprint0/sprint0/Room.cs
  sprint0/sprint0/RoomLoader/RoomBlocks.cs
  sprint0/sprint0/RoomLoader/RoomEnemies.cs
  sprint0/sprint0/RoomLoader/RoomItems.cs
  sprint0/sprint0/RoomLoader/RoomNPCs.cs
  sprint0/sprint0/RoomLoader/RoomProjectile.cs
  sprint0/sprint0/RoomLoader/RoomSound.cs
  sprint0/sprint0/RoomLoader/RoomSprite.cs
  sprint0/sprint0/RoomLoader/RoomWeapon.cs
  sprint0/sprint0/Weapons/Bomb.cs
  sprint0/sprint0/sprint0.csproj
Labels: new feature, refactor

#387 inventory, restricted item use, removed sound from level loader, and minor adjustments
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Dodongo/Dodongo.cs
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Bosses/Patra/PatraMinion.cs
  sprint0/sprint0/Collision/LinkItemCollisionHandler.cs
  sprint0/sprint0/Enemies/Enemy.cs
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/HUD/BombHUD.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDItem.cs
  sprint0/sprint0/HUD/HUDManager.cs
  sprint0/sprint0/HUD/KeyHUD.cs
  sprint0/sprint0/HUD/PauseScreenManager.cs
  sprint0/sprint0/HUD/RupeeHUD.cs
  sprint0/sprint0/Input/Command/FourCommand.cs
  sprint0/sprint0/Input/Command/OneCommand.cs
  sprint0/sprint0/Input/Command/SwordCommand.cs
  sprint0/sprint0/Input/Command/ThreeCommand.cs
  sprint0/sprint0/Input/Command/TwoCommand.cs
  sprint0/sprint0/LevelLoader.cs
  sprint0/sprint0/Link/DamagedLink.cs
  sprint0/sprint0/Link/Link.cs
  sprint0/sprint0/Link/LinkUseItemHelper.cs
  sprint0/sprint0/Room.cs
  sprint0/sprint0/RoomLoader/LoadLevel.cs
  sprint0/sprint0/Weapons/Bomb.cs
  sprint0/sprint0/sprint0.csproj
Labels: new feature, refactor
