Repository SnobbyDragon/CSE3902_SP21, pull requests merged in 2021-02, with the labels that each got.

#95 boss movements
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/BossesSpriteFactory.cs
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Gleek/GleeokHead.cs
  sprint0/sprint0/Bosses/Gleek/GleeokNeck.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokFireball.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokNeck.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Bosses/Patra/PatraMinion.cs
  sprint0/sprint0/Game1.cs
Labels: new feature

#112 wallmaster move
  sprint0/sprint0/Enemies/Wallmaster.cs
  sprint0/sprint0/Game1.cs
Labels: new feature

#110 keese, goriya, and goriya boomerang movement
  sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs
  sprint0/sprint0/Enemies/EnemyNPCSprites.cs
  sprint0/sprint0/Enemies/Goriya.cs
  sprint0/sprint0/Enemies/GoriyaBoomerang.cs
  sprint0/sprint0/Enemies/Keese.cs
Labels: refactor

#109 digdogger
  sprint0/sprint0/Bosses/BossesSpriteFactory.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/sprint0.csproj
Labels: new feature

#116 Added functionality to fire arrows
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/Input/Command/OneCommand.cs
  sprint0/sprint0/Input/Command/ThreeCommand.cs
  sprint0/sprint0/Input/Command/TwoCommand.cs
  sprint0/sprint0/Input/Controller/KeyboardController.cs
  sprint0/sprint0/Items/Arrow.cs
  sprint0/sprint0/Link/DamagedLink.cs
  sprint0/sprint0/Link/IPlayer.cs
  sprint0/sprint0/Link/Link.cs
  sprint0/sprint0/Link/States/DownIdleState.cs
  sprint0/sprint0/Link/States/IPlayerState.cs
  sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
Labels: new feature

#115 fireballs, 2.5 scale
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/Aquamentus/AquamentusFireball.cs
  sprint0/sprint0/Bosses/BossesSpriteFactory.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Ganon/GanonFireball.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokFireball.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs
  sprint0/sprint0/Bosses/Gleeok/GleeokNeck.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Manhandla/ManhandlaFireball.cs
  sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Bosses/Patra/PatraMinion.cs
  sprint0/sprint0/Dungeon/OpenDoor.cs
  sprint0/sprint0/Dungeon/RoomBorder.cs
  sprint0/sprint0/Dungeon/RoomFloor.cs
  sprint0/sprint0/Enemies/EnemyNPCSprites.cs
  sprint0/sprint0/Enemies/Wallmaster.cs
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/HUD/BombHUD.cs
  sprint0/sprint0/HUD/HUD.cs
  sprint0/sprint0/HUD/HUDFactory.cs
  sprint0/sprint0/HUD/HUDItemA.cs
  sprint0/sprint0/HUD/HUDItemB.cs
  sprint0/sprint0/HUD/HeartHUD.cs
  sprint0/sprint0/HUD/KeyHUD.cs
  sprint0/sprint0/HUD/RupeeHUD.cs
  sprint0/sprint0/Input/Command/ResetCommand.cs
Labels: new feature, refactor

#127 fix off screen for enemies
  sprint0/sprint0/Bosses/Dodongo/Dodongo.cs
  sprint0/sprint0/Enemies/EnemyNPCSprites.cs
  sprint0/sprint0/Enemies/Gel.cs
  sprint0/sprint0/Enemies/Goriya.cs
  sprint0/sprint0/Enemies/GoriyaBoomerang.cs
  sprint0/sprint0/Enemies/Keese.cs
  sprint0/sprint0/Enemies/Snake.cs
  sprint0/sprint0/Enemies/Stalfos.cs
  sprint0/sprint0/Enemies/Wallmaster.cs
  sprint0/sprint0/Enemies/Zol.cs
Labels: bug fix

#150 changed the movement of the boomerang so that it spins
  sprint0/sprint0/Enemies/GoriyaBoomerang.cs
  sprint0/sprint0/Items/Boomerang.cs
Labels: refactor
