Repository SnobbyDragon/CSE3902_SP21, pull requests merged in 2021-04, with the labels that each got.

#433 Death and Spawn animation for enemies, Zol Movement
  sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Dodongo/Dodongo.cs
  sprint0/sprint0/Bosses/Gleeok/Gleeok.cs
  sprint0/sprint0/Bosses/Gohma/Gohma.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Collision/EnemyEnemyCollisionHandler.cs
  sprint0/sprint0/Content/LevelData/Room3.xml
  sprint0/sprint0/Content/LevelData/Room9.xml
  sprint0/sprint0/Effects/EffectSpriteFactory.cs
  sprint0/sprint0/Enemies/AbstractEnemy.cs
  sprint0/sprint0/Enemies/DeathCloud.cs
  sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs
  sprint0/sprint0/Enemies/Gel.cs
  sprint0/sprint0/Enemies/Goriya.cs
  sprint0/sprint0/Enemies/Keese.cs
  sprint0/sprint0/Enemies/Snake.cs
  sprint0/sprint0/Enemies/SpawnCloud.cs
  sprint0/sprint0/Enemies/Stalfos.cs
  sprint0/sprint0/Enemies/Trap.cs
  sprint0/sprint0/Enemies/Wallmaster.cs
  sprint0/sprint0/Enemies/Zol.cs
  sprint0/sprint0/LevelLoader.cs
  sprint0/sprint0/RoomLoader/LoadLevel.cs
  sprint0/sprint0/RoomLoader/RoomEffect.cs
  sprint0/sprint0/RoomLoader/RoomEnemies.cs
Labels: bug fix, new feature

#441 Snake Bug
  sprint0/sprint0/Enemies/Snake.cs
Labels: bug fix

#446 Merchant
  sprint0/sprint0/Content/LevelData/Room4.xml
Labels: new feature

#444 Triforce in Ganon Ashes
  sprint0/sprint0/Bosses/Ganon/Ganon.cs
  sprint0/sprint0/Bosses/Ganon/GanonAshes.cs
  sprint0/sprint0/Collision/LinkItemCollisionHandler.cs
  sprint0/sprint0/Effects/EffectSpriteFactory.cs
  sprint0/sprint0/Items/GanonTriforceAshes.cs
  sprint0/sprint0/Items/ItemsSpriteFactory.cs
Labels: new feature

#451 Boomerang and Sword Enemy Collision
  sprint0/sprint0/Collision/EnemyWeaponCollisionHandler.cs
  sprint0/sprint0/Weapons/Boomerang.cs
  sprint0/sprint0/Weapons/Sword.cs
Labels: bug fix

#442 Goriya Boomerang Removal
  sprint0/sprint0/Enemies/Goriya.cs
  sprint0/sprint0/Weapons/Boomerang.cs
Labels: bug fix

#447 Colored Fireballs
  sprint0/sprint0/Weapons/Fireball.cs
  sprint0/sprint0/Weapons/ProjectileSpriteFactory.cs
Labels: new feature

#455 Trap Movement
  sprint0/sprint0/Enemies/Trap.cs
Labels: bug fix

#454 Arrow Hitbox
  sprint0/sprint0/Weapons/Arrow.cs
Labels: bug fix

#464 EnemyBorderCollision
  sprint0/sprint0/Collision/AllCollisionHandler.cs
  sprint0/sprint0/Collision/EnemyBorderCollisionHandler.cs
Labels: bug fix

#465 max health, link spawn, item bug fix
  sprint0/sprint0/Content/LevelData/Room12.xml
  sprint0/sprint0/Content/LevelData/Room13.xml
  sprint0/sprint0/Content/LevelData/Room18.xml
  sprint0/sprint0/Content/LevelData/Room2.xml
  sprint0/sprint0/Content/LevelData/Room3.xml
  sprint0/sprint0/Content/LevelData/Room4.xml
  sprint0/sprint0/Content/LevelData/Room6.xml
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDItem.cs
  sprint0/sprint0/HUD/HUDItemMapping.cs
  sprint0/sprint0/HUD/HUDManager.cs
  sprint0/sprint0/HUD/HeartHUD.cs
  sprint0/sprint0/HUD/ItemSelection.cs
  sprint0/sprint0/Link/Link.cs
Labels: bug fix, refactor

#482 Link Spawn Location
  sprint0/sprint0/GameState/GameStateMachine.cs
  sprint0/sprint0/LevelLoader.cs
  sprint0/sprint0/RoomLoader/LoadLevel.cs
Labels: bug fix

#483 red candle also shoots flames
  sprint0/sprint0/Input/Command/FourCommand.cs
Labels: new feature

#484 compass isn't holdable b item
  sprint0/sprint0/HUD/HUDItem.cs
Labels: bug fix

#503 fixed map. added functionality for rooms 19, 20, and 21
  sprint0/sprint0/Game1.cs
  sprint0/sprint0/HUD/HUDMiniMapping.cs
  sprint0/sprint0/Screen/Pause/PauseScreenMapping.cs
Labels: bug fix, new feature

#504 some item functions
  sprint0/sprint0/Content/LevelData/Room18.xml
  sprint0/sprint0/Content/LevelData/Room9.xml
  sprint0/sprint0/HUD/HUDMiniMap.cs
  sprint0/sprint0/Input/Command/BItemCommand.cs
  sprint0/sprint0/Input/Command/FourCommand.cs
  sprint0/sprint0/Input/Command/RodCommand.cs
  sprint0/sprint0/Input/Command/SwordCommand.cs
  sprint0/sprint0/Input/Controller/KeyboardItemController.cs
  sprint0/sprint0/Link/Link.cs
  sprint0/sprint0/Link/LinkUseItemHelper.cs
  sprint0/sprint0/Screen/Pause/PauseScreenMap.cs
  sprint0/sprint0/Screen/Pause/PauseScreenMapping.cs
Labels: bug fix, new feature

#536 fixed the boss scree at beginning. only 1 digdoggers instead of 3
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/Bosses/Manhandla/Manhandla.cs
  sprint0/sprint0/Bosses/Patra/Patra.cs
  sprint0/sprint0/Content/LevelData/Room7.xml
Labels: bug fix

#537 fixed blue potion not being used bug, minus 1 for scrolling offset
  sprint0/sprint0/Collision/LinkItemCollisionHandler.cs
  sprint0/sprint0/GameState/GameStateMachine.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDItem.cs
  sprint0/sprint0/HUD/HUDItemMapping.cs
  sprint0/sprint0/HUD/HUDManager.cs
  sprint0/sprint0/HUD/MainHUD.cs
  sprint0/sprint0/Input/Command/BItemCommand.cs
  sprint0/sprint0/Input/Command/PotionCommand.cs
  sprint0/sprint0/Interfaces/IItem.cs
  sprint0/sprint0/Items/AbstractItem.cs
  sprint0/sprint0/Items/ArrowItem.cs
  sprint0/sprint0/Items/BlueBoomerangItem.cs
  sprint0/sprint0/Items/BlueCandle.cs
  sprint0/sprint0/Items/BluePotion.cs
  sprint0/sprint0/Items/BlueRing.cs
  sprint0/sprint0/Items/BoomerangItem.cs
  sprint0/sprint0/Items/Candle.cs
  sprint0/sprint0/Items/Fairy.cs
  sprint0/sprint0/Items/GanonTriforceAshes.cs
  sprint0/sprint0/Items/Potion.cs
  sprint0/sprint0/Items/Ring.cs
  sprint0/sprint0/Items/TriforcePiece.cs
  sprint0/sprint0/Link/IPlayer.cs
Labels: bug fix

#541 change sword using 'F', flute function
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDManager.cs
  sprint0/sprint0/Input/Command/BItemCommand.cs
  sprint0/sprint0/Input/Command/ChangeSwordCommand.cs
  sprint0/sprint0/Input/Command/FluteCommand.cs
  sprint0/sprint0/Input/Controller/KeyboardController.cs
  sprint0/sprint0/RoomLoader/RoomEnemies.cs
Labels: new feature

#538 fixed one of the magical rod bugs
  sprint0/sprint0/Input/Command/RodCommand.cs
  sprint0/sprint0/Input/Command/SwordCommand.cs
  sprint0/sprint0/Link/DamagedLink.cs
  sprint0/sprint0/Link/IPlayer.cs
  sprint0/sprint0/Link/Link.cs
  sprint0/sprint0/Link/LinkUseItemHelper.cs
  sprint0/sprint0/Link/States/DownIdleState.cs
  sprint0/sprint0/Link/States/IPlayerState.cs
  sprint0/sprint0/Link/States/LeftIdleState.cs
  sprint0/sprint0/Link/States/RightIdleState.cs
  sprint0/sprint0/Link/States/UpIdleState.cs
Labels: bug fix

#543 potions completely replenishes link's health
  sprint0/sprint0/Input/Command/PotionCommand.cs
  sprint0/sprint0/Items/StepLadder.cs
Labels: new feature

#554 maze room
  sprint0/sprint0/Collision/AllCollisionHandler.cs
  sprint0/sprint0/Collision/BlockBlockCollisionDetector.cs
  sprint0/sprint0/Collision/BlockBlockCollisionHandler.cs
  sprint0/sprint0/Collision/CollisionDetector.cs
  sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs
  sprint0/sprint0/Content/LevelData/Room20.xml
  sprint0/sprint0/Content/LevelData/Room21.xml
  sprint0/sprint0/Dungeon/AbstractBlock.cs
  sprint0/sprint0/Dungeon/DungeonFactory.cs
  sprint0/sprint0/Dungeon/InvisibleBlock.cs
  sprint0/sprint0/Dungeon/MovableBlock1.cs
  sprint0/sprint0/Dungeon/MovableBlock20.cs
  sprint0/sprint0/Dungeon/MovableBlock5.cs
  sprint0/sprint0/Dungeon/Statue.cs
  sprint0/sprint0/Interfaces/IBlock.cs
  sprint0/sprint0/Items/Fairy.cs
  sprint0/sprint0/LevelLoader.cs
  sprint0/sprint0/Room.cs
  sprint0/sprint0/RoomLoader/RoomBlocks.cs
Labels: bug fix, new feature

#556 digdogger, hud
  sprint0/sprint0/Bosses/Digdogger/Digdogger.cs
  sprint0/sprint0/HUD/BombHUD.cs
  sprint0/sprint0/HUD/HUDCounterItems.cs
  sprint0/sprint0/HUD/HUDFactory.cs
  sprint0/sprint0/HUD/HUDInventory.cs
  sprint0/sprint0/HUD/HUDInventoryHelper.cs
  sprint0/sprint0/HUD/HeartHUD.cs
  sprint0/sprint0/HUD/KeyHUD.cs
  sprint0/sprint0/HUD/RupeeHUD.cs
  sprint0/sprint0/Interfaces/IHUDInventory.cs
  sprint0/sprint0/Items/ArrowItem.cs
  sprint0/sprint0/NPCs/Merchant.cs
  sprint0/sprint0/NPCs/NpcsSpriteFactory.cs
  sprint0/sprint0/NPCs/OldPerson.cs
Labels: bug fix, new feature

#572 Dark Room
  sprint0/sprint0/Content/Images/DungeonTileset.png
  sprint0/sprint0/Content/LevelData/Level1/Room5.xml
  sprint0/sprint0/Dungeon/DarkRoom.cs
  sprint0/sprint0/Dungeon/DungeonFactory.cs
Labels: new feature
